import { chromium } from 'playwright';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const presetRaw = JSON.parse(readFileSync(process.env.PRESET_FILE, 'utf8'));
const configuration = typeof presetRaw.configuration === 'string' ? JSON.parse(presetRaw.configuration) : presetRaw.configuration;
const task = configuration?.tasks?.[0] ?? configuration;
if (!task || !Array.isArray(task.actions)) throw new Error('Preset did not contain a renderable task.');
mkdirSync('verification', { recursive: true }); mkdirSync('assets', { recursive: true });
const serializedTask = JSON.stringify(task).replace(/<\/script/gi, '<\\/script');
writeFileSync('verification/embed-test.html', `<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;background:#0b0b0b}body{padding:28px;box-sizing:border-box}#frame{width:1384px;height:780px;margin:0 auto;overflow:hidden;border-radius:16px;background:#020202}</style></head><body><div id="frame"><div id="embed"></div></div><script type="module">import { mountFigraniumEmbed } from '/dist/index.js';mountFigraniumEmbed('#embed',{task:${serializedTask},height:780,autoResize:false,title:'Google Maps Lead Scraper'});</script></body></html>`);
const browser = await chromium.launch({headless:true}); const page = await browser.newPage({viewport:{width:1440,height:860}});
await page.goto('http://127.0.0.1:4173/verification/embed-test.html',{waitUntil:'networkidle'});
const iframe = await page.waitForSelector('#embed iframe'); const frame = await iframe.contentFrame(); if(!frame) throw new Error('No iframe');
await frame.waitForSelector('.figranium-readonly-canvas');
const dot = await frame.locator('.figranium-readonly-canvas').evaluate(el => getComputedStyle(el).getPropertyValue('--app-dot').trim());
if (!dot) throw new Error('Figranium dot-grid token is missing');
const grid = await frame.locator('.figranium-readonly-canvas .absolute.inset-0.pointer-events-none.z-0').first().evaluate(el => getComputedStyle(el).backgroundImage);
if (!grid.includes('radial-gradient')) throw new Error(`Dot grid is not rendered: ${grid}`);
const font = await frame.locator('body').evaluate(el => getComputedStyle(el).fontFamily);
if (!font.toLowerCase().includes('questrial')) throw new Error(`Figranium font missing: ${font}`);
await page.locator('#frame').screenshot({path:'assets/google-maps-leads-scraper.png'});
console.log({dot,grid,font,actions:task.actions.length}); await browser.close();